# ---folders---
data_path: "/Users/ranweisman/PycharmProjects/nn-ambisonics-upscaler/data/raw/image-method"
logs_path: "/Users/ranweisman/PycharmProjects/nn-ambisonics-upscaler/experiments"
experiment_name: "some_experiment_name"
# ---network structure---
model_name: "fc"
hidden_layers: 3
hidden_sizes:
- 1600
- 2700
- 3800
# ---data---
batch_size: 10
num_workers: 6
train_val_split:
- 0.8
- 0.2
# ---optimization---
lr: 0.0003
max_epochs: 2
gpus: 0
