# ---folders---
data_path: "/Users/ranweisman/Google Drive/My Drive/My Documents/MATLAB/Research/nn-ambisonics-upscaler/raw/free-field"
logs_path: "/Users/ranweisman/PycharmProjects/nn-ambisonics-upscaler/experiments"
# ---network structure---
input_size: 512
output_size: 4802
output_shape:
- 2
- 49
- 49
hidden_layers: 3
hidden_sizes:
- 1600
- 2700
- 3800
# ---data---
batch_size: 10
num_workers: 6
train_val_split:
- 0.8
- 0.2
# ---optimization---
lr: 0.0003
max_epochs: 2
gpus: 0
